## data
data_file: /data/shuqili/aloha_pretrain_datasets/v0_pretrained_dataset_96_without_missing_data.npy

## model
seq_len: 96
label_len: 96
stride: 12
patch_len: 12

## training
per_device_train_batch_size: 3840
per_device_eval_batch_size: 3840
adam_eps: 1.0e-8
weight_decay: 0.01
max_grad_norm: 1.0
lr: 0.0001
max_train_epochs: 100
seed: 19980406
gradient_accumulation_steps: 4
val_check_interval: 1.0
pct_start: 0.12
mask_ratio: 0.4
num_channels: 1
